name = "promptbazaarai"
compatibility_date = "2024-09-15"
pages_build_output_dir = "dist"

[vars]
SUPABASE_URL = "https://mnqkeoeikfjwlgyowsnb.supabase.co"

[env.production.vars]
SUPABASE_URL = "https://mnqkeoeikfjwlgyowsnb.supabase.co"
