name = "banglaprompt-ai"
compatibility_date = "2024-09-15"
pages_build_output_dir = "dist"

[vars]
# MY_VARIABLE = "production_value"
SUPABASE_URL = "https://mnqkeoeikfjwlgyowsnb.supabase.co"

[env.production.vars]
# MY_VARIABLE = "production_value"
SUPABASE_URL = "https://mnqkeoeikfjwlgyowsnb.supabase.co"
